class APIUtils {

    constructor(apiContext, loginPayload) {
        this.apiContext = apiContext;
        this.loginPayload = loginPayload;
    }

    async getToken() {
        const loginResponse = await this.apiContext.post("https://rahulshettyacademy.com/api/ecom/auth/login",
            {
                data: this.loginPayload
            });


        const loginJson = await loginResponse.json();

        const token = loginJson.token;
        console.log("Login Token Generated by API:" + token);
        return token;
    }

    async createOrder(orderPayload) {
        let response = {};
        response.token = await this.getToken();
        const orderResponse = await this.apiContext.post("https://rahulshettyacademy.com/api/ecom/order/create-order", {
            data: orderPayload,
            headers: {
                'authorization': response.token,
                'content-type': 'application/json'
            }
        });

        const orderResponseJson = await orderResponse.json();
        const orderId = orderResponseJson.orders[0];
        console.log("Order created by API and Order ID : " + orderId);
        response.orderId = orderId;
        return response;
    }

    async deleteOrder(token ,orderId) {
    const orderDelete = await this.apiContext.delete('https://rahulshettyacademy.com/api/ecom/order/delete-order/' + orderId, {
        headers: {
            'authorization': token,
            'content-type': 'application/json'
        }
    });
    const orderDeleteResponse = await orderDelete.json();
    const message = orderDeleteResponse.message;
    return message;
    // await expect(message === 'Orders Deleted Successfully').toBeTruthy();
} 
}

module.exports = { APIUtils };